name: Daily TSLA Analysis

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run analysis
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      run: python scripts/daily_analysis.py
    - name: Commit results
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add results/
        git commit -m "Add daily TSLA analysis for $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push 